CREATE USER app_back_end WITH ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE user_service TO app_back_end;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS plpgsql;